version: 2.0

jobs:
  unit-tests:
    working_directory: /go/src/s32x.com/httpclient
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go test ./...
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests